include: package:flutter_lints/flutter.yaml

plugins:
  riverpod_lint: ^3.1.4

linter:
  rules:
    always_use_package_imports: true
    avoid_multiple_declarations_per_line: true
    avoid_print: true
    avoid_redundant_argument_values: true
    eol_at_end_of_file: true
    lines_longer_than_80_chars: true
    prefer_single_quotes: true
    prefer_final_locals: true
    secure_pubspec_urls: true
    unnecessary_null_checks: true
    unnecessary_statements: true
    unnecessary_this: true
    use_full_hex_values_for_flutter_colors: true
    valid_regexps: true